"""add_overall_defended_columns

Revision ID: 3593e9dc9c82
Revises: 8ed42745715f
Create Date: 2026-07-08 20:53:18.966905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3593e9dc9c82'
down_revision: Union[str, None] = '8ed42745715f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_season_stats', sa.Column('d_fga', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('d_plusminus', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_season_stats', 'd_plusminus')
    op.drop_column('player_season_stats', 'd_fga')
    # ### end Alembic commands ###
