"""add advanced stat columns to player_season_stats

Revision ID: 44741ceede16
Revises: ef043f7a9e23
Create Date: 2026-06-23 18:28:06.851948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44741ceede16'
down_revision: Union[str, None] = 'ef043f7a9e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_season_stats', sa.Column('ast_pct', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('oreb_pct', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('dreb_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_season_stats', 'dreb_pct')
    op.drop_column('player_season_stats', 'oreb_pct')
    op.drop_column('player_season_stats', 'ast_pct')
    # ### end Alembic commands ###
