"""add_foul_drawing_rate_to_player_tendencies

Revision ID: 529b31a8f50f
Revises: m3b_add_oreb_pct
Create Date: 2026-07-07 23:46:03.027788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529b31a8f50f'
down_revision: Union[str, None] = 'm3b_add_oreb_pct'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_tendencies', sa.Column('foul_drawing_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_tendencies', 'foul_drawing_rate')
    # ### end Alembic commands ###
