"""add oreb_rate dreb_rate to player_tendencies

Revision ID: 6a496f313abc
Revises: 44741ceede16
Create Date: 2026-06-23 18:29:11.469092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a496f313abc'
down_revision: Union[str, None] = '44741ceede16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_tendencies', sa.Column('oreb_rate', sa.Float(), nullable=True))
    op.add_column('player_tendencies', sa.Column('dreb_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_tendencies', 'dreb_rate')
    op.drop_column('player_tendencies', 'oreb_rate')
    # ### end Alembic commands ###
