"""simulation tables: lineup_players, simulation_runs, simulated_games, simulated_player_lines

Revision ID: 759f4ff705b5
Revises: 0002
Create Date: 2026-06-23 16:30:27.643737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759f4ff705b5'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('games_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineup_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('minutes_per_game', sa.Float(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'team_id', 'player_id', name='uq_lp_sim_team_player')
    )
    op.create_index(op.f('ix_lineup_players_simulation_id'), 'lineup_players', ['simulation_id'], unique=False)
    op.create_table('simulated_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_q1', sa.Integer(), nullable=False),
    sa.Column('home_q2', sa.Integer(), nullable=False),
    sa.Column('home_q3', sa.Integer(), nullable=False),
    sa.Column('home_q4', sa.Integer(), nullable=False),
    sa.Column('away_q1', sa.Integer(), nullable=False),
    sa.Column('away_q2', sa.Integer(), nullable=False),
    sa.Column('away_q3', sa.Integer(), nullable=False),
    sa.Column('away_q4', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'game_id', name='uq_sg_sim_game')
    )
    op.create_index(op.f('ix_simulated_games_simulation_id'), 'simulated_games', ['simulation_id'], unique=False)
    op.create_table('simulated_player_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulated_game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fg3m', sa.Integer(), nullable=False),
    sa.Column('fg3a', sa.Integer(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['simulated_game_id'], ['simulated_games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulated_game_id', 'player_id', name='uq_spl_game_player')
    )
    op.create_index(op.f('ix_simulated_player_lines_simulated_game_id'), 'simulated_player_lines', ['simulated_game_id'], unique=False)
    op.alter_column('player_attributes', 'three_point',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('40'))
    op.alter_column('player_attributes', 'free_throw',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('40'))
    op.alter_column('player_attributes', 'mid_range',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('40'))
    op.alter_column('player_attributes', 'close_shot',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'layup',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'dunk',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'passing',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'ball_handle',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'steal',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'block',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'perimeter_defense',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'interior_defense',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'speed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'acceleration',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'strength',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'stamina',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'vertical',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'offensive_rebound',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'defensive_rebound',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'overall_rating',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_attributes', 'overall_rating',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'defensive_rebound',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'offensive_rebound',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'vertical',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'stamina',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'strength',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'acceleration',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'speed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'interior_defense',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'perimeter_defense',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'block',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'steal',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'ball_handle',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'passing',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'dunk',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'layup',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'close_shot',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('player_attributes', 'mid_range',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('40'))
    op.alter_column('player_attributes', 'free_throw',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('40'))
    op.alter_column('player_attributes', 'three_point',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('40'))
    op.drop_index(op.f('ix_simulated_player_lines_simulated_game_id'), table_name='simulated_player_lines')
    op.drop_table('simulated_player_lines')
    op.drop_index(op.f('ix_simulated_games_simulation_id'), table_name='simulated_games')
    op.drop_table('simulated_games')
    op.drop_index(op.f('ix_lineup_players_simulation_id'), table_name='lineup_players')
    op.drop_table('lineup_players')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
