"""add_quarter_line_scores_to_games

Revision ID: 7e31a42e2e16
Revises: 3593e9dc9c82
Create Date: 2026-07-09 16:21:47.352212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e31a42e2e16'
down_revision: Union[str, None] = '3593e9dc9c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_q1', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_q2', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_q3', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_q4', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_ot', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_q1', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_q2', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_q3', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_q4', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_ot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'away_ot')
    op.drop_column('games', 'away_q4')
    op.drop_column('games', 'away_q3')
    op.drop_column('games', 'away_q2')
    op.drop_column('games', 'away_q1')
    op.drop_column('games', 'home_ot')
    op.drop_column('games', 'home_q4')
    op.drop_column('games', 'home_q3')
    op.drop_column('games', 'home_q2')
    op.drop_column('games', 'home_q1')
    # ### end Alembic commands ###
