"""add_corner_three_rate_to_player_tendencies

Revision ID: 8ed42745715f
Revises: a430c45fbf57
Create Date: 2026-07-08 20:33:36.450367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed42745715f'
down_revision: Union[str, None] = 'a430c45fbf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_tendencies', sa.Column('corner_three_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_tendencies', 'corner_three_rate')
    # ### end Alembic commands ###
