"""add_shot_location_and_defense_observations

Revision ID: a430c45fbf57
Revises: 529b31a8f50f
Create Date: 2026-07-08 20:32:03.162345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a430c45fbf57'
down_revision: Union[str, None] = '529b31a8f50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_season_stats', sa.Column('ra_fgm', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('ra_fga', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('ra_fg_pct', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('paint_fgm', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('paint_fga', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('paint_fg_pct', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('mid_fga', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('mid_fg_pct', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('corner3_fga', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('d_lt6_fga', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('d_lt6_plusminus', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('d_fg3a', sa.Float(), nullable=True))
    op.add_column('player_season_stats', sa.Column('d_fg3_plusminus', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_season_stats', 'd_fg3_plusminus')
    op.drop_column('player_season_stats', 'd_fg3a')
    op.drop_column('player_season_stats', 'd_lt6_plusminus')
    op.drop_column('player_season_stats', 'd_lt6_fga')
    op.drop_column('player_season_stats', 'corner3_fga')
    op.drop_column('player_season_stats', 'mid_fg_pct')
    op.drop_column('player_season_stats', 'mid_fga')
    op.drop_column('player_season_stats', 'paint_fg_pct')
    op.drop_column('player_season_stats', 'paint_fga')
    op.drop_column('player_season_stats', 'paint_fgm')
    op.drop_column('player_season_stats', 'ra_fg_pct')
    op.drop_column('player_season_stats', 'ra_fga')
    op.drop_column('player_season_stats', 'ra_fgm')
    # ### end Alembic commands ###
