"""season_sim_schema_v2

Revision ID: aa432dca8ec4
Revises: 6a496f313abc
Create Date: 2026-06-25 15:44:46.447375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa432dca8ec4'
down_revision: Union[str, None] = '6a496f313abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulated_games', sa.Column('went_to_ot', sa.Boolean(), nullable=False))
    op.add_column('simulated_games', sa.Column('quarter_scores', sa.JSON(), nullable=False))
    op.drop_column('simulated_games', 'away_q3')
    op.drop_column('simulated_games', 'home_q3')
    op.drop_column('simulated_games', 'away_q4')
    op.drop_column('simulated_games', 'home_q2')
    op.drop_column('simulated_games', 'home_q1')
    op.drop_column('simulated_games', 'home_q4')
    op.drop_column('simulated_games', 'away_q2')
    op.drop_column('simulated_games', 'away_q1')
    op.add_column('simulated_player_lines', sa.Column('personal_fouls', sa.Integer(), nullable=False))
    op.add_column('simulated_player_lines', sa.Column('fouled_out', sa.Boolean(), nullable=False))
    op.add_column('simulation_runs', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_simulation_runs_team_id'), 'simulation_runs', ['team_id'], unique=False)
    op.create_foreign_key(None, 'simulation_runs', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulation_runs', type_='foreignkey')
    op.drop_index(op.f('ix_simulation_runs_team_id'), table_name='simulation_runs')
    op.drop_column('simulation_runs', 'team_id')
    op.drop_column('simulated_player_lines', 'fouled_out')
    op.drop_column('simulated_player_lines', 'personal_fouls')
    op.add_column('simulated_games', sa.Column('away_q1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('simulated_games', sa.Column('away_q2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('simulated_games', sa.Column('home_q4', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('simulated_games', sa.Column('home_q1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('simulated_games', sa.Column('home_q2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('simulated_games', sa.Column('away_q4', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('simulated_games', sa.Column('home_q3', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('simulated_games', sa.Column('away_q3', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('simulated_games', 'quarter_scores')
    op.drop_column('simulated_games', 'went_to_ot')
    # ### end Alembic commands ###
