"""add clutch_rating to player_attributes

Revision ID: be759481a4d9
Revises: e1580915be22
Create Date: 2026-06-27 02:37:47.165251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be759481a4d9'
down_revision: Union[str, None] = 'e1580915be22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_attributes', sa.Column('clutch_rating', sa.Integer(), server_default='50', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_attributes', 'clutch_rating')
    # ### end Alembic commands ###
