"""add game_scoring_events

Revision ID: be9c7772bbc7
Revises: 7e31a42e2e16
Create Date: 2026-07-14 05:49:18.099913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9c7772bbc7'
down_revision: Union[str, None] = '7e31a42e2e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_scoring_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('event_num', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('seconds_remaining', sa.Integer(), nullable=False),
    sa.Column('scoring_side', sa.String(length=4), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scoring_events_game_order', 'game_scoring_events', ['game_id', 'event_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scoring_events_game_order', table_name='game_scoring_events')
    op.drop_table('game_scoring_events')
    # ### end Alembic commands ###
