"""add usg_pct to player_season_stats

Revision ID: ef043f7a9e23
Revises: 759f4ff705b5
Create Date: 2026-06-23 17:43:25.320989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef043f7a9e23'
down_revision: Union[str, None] = '759f4ff705b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_season_stats', sa.Column('usg_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_season_stats', 'usg_pct')
    # ### end Alembic commands ###
